---
# required data | before | download | local | redis_exporter
- name: required data | before | download | local | redis_exporter
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - "{{ redis_exporter_required_data_before_download_local }}"
  run_once: True
  delegate_to: localhost
  when: redis_exporter_required_data_before_download_local is defined
