---
# set variables
- include_tasks: "{{ role_path }}/tasks/common/set_variables.yml"

# include variables
- include_tasks: "{{ role_path }}/tasks/common/include_variables.yml"

# sysctl conf
- include_tasks: "{{ role_path }}/tasks/common/update_sysctl_conf.yml"

# security limits
- include_tasks: "{{ role_path }}/tasks/common/update_security_limits_conf.yml"

# required directory
- include_tasks: "{{ role_path }}/tasks/common/required_directory.yml"

# required data
- include_tasks: "{{ role_path }}/tasks/common/required_data.yml"

# update hosts
- include_tasks: "{{ role_path }}/tasks/common/update_hosts.yml"

# update conf
- include_tasks: "{{ role_path }}/tasks/common/update_conf.yml"
