---
# set variables
- include_tasks: "{{ role_path }}/tasks/common/set_variables.yml"

# include variables
- include_tasks: "{{ role_path }}/tasks/common/include_variables.yml"

# update sysctl.conf
- include_tasks: "{{ role_path }}/tasks/common/update_sysctl_conf.yml"

# update security limits.conf
- include_tasks: "{{ role_path }}/tasks/common/update_security_limits_conf.yml"

# include distribution
- include_tasks: "{{ role_path }}/tasks/common/include_distribution.yml"

# required directory
- include_tasks: "{{ role_path }}/tasks/common/required_directory.yml"

# required data | before
- include_tasks: "{{ role_path }}/tasks/common/required_data_before.yml"

# required data
- include_tasks: "{{ role_path }}/tasks/common/required_data.yml"

# unarchive data
- include_tasks: "{{ role_path }}/tasks/common/unarchive_data.yml"

# install package
- include_tasks: "{{ role_path }}/tasks/distribution/{{ distribution }}/required_package.yml"

# required data | after
- include_tasks: "{{ role_path }}/tasks/common/required_data_after.yml"

# systemd
- include_tasks: "{{ role_path }}/tasks/common/systemd.yml"

# cleanup
- include_tasks: "{{ role_path }}/tasks/common/cleanup.yml"
