---
lvm_filesystem:
- vg: "data"
  lv: "data"
  size: "100%FREE"
  pvs: "/dev/sdb"
  pesize: "4"
  shrink: no
  force: no
  fstype: xfs
  dev: /dev/data/data

- vg: "backup"
  lv: "backup"
  size: "100%FREE"
  pvs: "/dev/sdc"
  pesize: "4"
  shrink: no
  force: no
  fstype: xfs
  dev: /dev/backup/backup
